import Head from 'next/head'
import APP from '../../constants'

export default function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>{APP.projectName}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>{children}</main>
    </>
  )
}
